# Generated by Django 4.0.4 on 2022-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Alumni meet', 'Alumni meet'), ('Training', 'Training'), ('Event', 'Event')], default='Alumni meet', max_length=100),
            preserve_default=False,
        ),
    ]
