# Generated by Django 4.0.2 on 2022-04-25 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DashBoard', '0003_joboffer_postedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('course', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('courseDuration', models.IntegerField()),
                ('tenthPercentage', models.IntegerField()),
                ('twelthPercentage', models.IntegerField()),
                ('contactNo', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('courseDeatils', models.CharField(max_length=100)),
                ('yearOfPassing', models.IntegerField()),
                ('yearOfJoining', models.IntegerField()),
                ('jobStatus', models.CharField(max_length=100)),
                ('contactNo', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
